name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dvc[s3]"
          pip install -r requirements.txt

      - name: Pull Model from S3 via DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # 1. Update the default region here
          AWS_DEFAULT_REGION: us-east-2
        run: |
          # 2. Update DVC to use the correct region
          dvc remote modify myremote --local access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote --local secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc remote modify myremote region us-east-2
          
          # Force DVC to use simple S3 calls
          dvc remote modify myremote --local s3_addressing_style path
          dvc remote modify myremote --local credentialpath ""
          
          # Pull the model
          dvc pull -v

      - name: Verify Model File
        run: ls -lh models/

      - name: Build Docker image
        run: docker build -t housing-price-api .